server:
  port: 8081
#30 min
accessTokenAvailableValidityPeriodInSec: 1800
#30 days
refreshTokenAvailableValidityPeriodInSec: 2592000

security-lib:
  refresh-token:
    mode:
      allowed-refresh-access: false

