grpc:
  client:
    user-service-grpc-client:
      address: static://localhost:9092
      negotiation-type: plaintext
    gateway-service-grpc-client:
      address: static://localhost:9090
      negotiation-type: plaintext
  server:
    port: 9091

security-lib:
  refresh-token:
    mode:
      allowed-refresh-access: false
  secret:
    key:
      internal: f8G7YxZ2KmL9QaP5RsDcVb3WNeJh4Tu1
      jwt: XyR9LpD0VwgCTb35KqNZzHaFs1MJvOU2
  black-list:
    enabled: true

server:
  port: 8081

spring:
  data:
    redis:
      port: 6379
      host: localhost

logging:
  level:
    root: DEBUG # всё приложение в режиме DEBUG
    org.springframework: INFO # можно оставить INFO, иначе много шума
    org.springframework.boot.autoconfigure: INFO # покажет, какие автоконфигурации включаются
    org.springframework.cloud.gateway: DEBUG # логика Gateway
    org.springframework.data.redis: DEBUG # Redis-соединения
    io.lettuce.core: WARN # понижаем шум от клиента Redis (или DEBUG, если нужно)
    com.bestStore: DEBUG # твой код
    sun: info
    javax.management: info