server:
  port: 8080

spring:
  application:
    name: notification-service
  mail:
    host: ${MAIL.HOST}
    port: ${MAIL.PORT}
    username: ${MAIL.USERNAME}
    password: ${MAIL.PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always