spring:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  datasource:
    username: ${DB_USERNAME}
    url: ${DB_URL}
    driver-class-name: org.postgresql.Driver
    password: ${DB_PASSWORD}
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.yaml
springdoc:
  swagger-ui:
    path: /docs/swagger-ui.html
  api-docs:
    path: /docs/api-docs
