spring:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/catalog_service
    driver-class-name: org.postgresql.Driver
    password: postgres
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.yaml
springdoc:
  swagger-ui:
    path: /docs/swagger-ui.html
  api-docs:
    path: /docs/api-docs
