services:
  - name: auth-service
    type: web
    runtime: docker
    repo: https://github.com/IhorMurashko/best-online-store
    branch: main
    rootDir: auth-service
    dockerContext: ./auth-service
    dockerfilePath: Dockerfile
    autoDeploy: false

  - name: user-service
    type: web
    runtime: docker
    repo: https://github.com/IhorMurashko/best-online-store
    branch: main
    rootDir: user-service
    dockerContext: ./user-service
    dockerfilePath: Dockerfile
    autoDeploy: false

  - name: gateway-service
    type: web
    runtime: docker
    repo: https://github.com/IhorMurashko/best-online-store
    branch: main
    rootDir: gateway-service
    dockerContext: ./gateway-service
    dockerfilePath: Dockerfile
    autoDeploy: false
