server:
  port: 8080
spring:
  application:
    name: cart-service
  profiles:
    active: dev
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always